---
- hosts: servers
  become: true
  tasks:
  - name: Install unrar
    apt: name=unrar force_apt_get=yes update_cache=yes state=present
  - name: Add hadoop
    user:
     name: hadoop
  - name: send files for installation
    copy: src=installl.rar dest/home/hadoop/Desktop/ follow=yes mode=preserve
  - name: Extract installl.rar
    command: 
     cmd: unrar x -r /home/user/Desktop/installl.rar /home/user/Desktop/
  - name: run shell script
    command: 
     cmd: sh /home/user/Desktop/installl/runme.sh
